import fs from 'node:fs';import zlib from 'node:zlib';import {test} from 'node:test';import assert from 'node:assert/strict';import {wgs84ToRD,setBathymetry,bottomAt,depthAt,basinAt,bathymetryDataUrl,refreshBathymetry,getBathymetryMetadata} from './bathymetry.js';
const data=JSON.parse(zlib.gunzipSync(fs.readFileSync(new URL('./data/bathymetry-ijsselmeer.json.gz',import.meta.url))));setBathymetry(data);const p={lat:52.73,lon:5.30},now=Date.now();
test('RD projection agrees with five pyproj reference points within one metre',()=>{for(const p of JSON.parse(fs.readFileSync(new URL('./data/bathymetry-projection-controls.json',import.meta.url)))){const q=wgs84ToRD(p);assert.ok(Math.hypot(q.x-p.x,q.y-p.y)<1);}});
test('historical grid and NAP water level combine without datum confusion',()=>{const b=bottomAt(p);assert.equal(b.unknown,false);assert.equal(b.surveyYear,2022);const r=depthAt(p,[{...p,valueM:-.3,time:now}],{now});assert.equal(r.depthM,-.3-b.bottomNapM);assert.equal(r.estimated,true);});
test('missing, stale, spatially distant water levels remain unknown',()=>{for(const levels of [[],[{...p,valueM:-.3,time:0}],[{lat:51,lon:4,valueM:-.3,time:now}]])assert.equal(depthAt(p,levels,{now}).unknown,true);});
test('lowest valid nearby level is used instead of higher optimistic level',()=>{const r=depthAt(p,[{...p,valueM:-.2,time:now},{...p,valueM:-.4,time:now}],{now});assert.equal(r.waterLevelNapM,-.4);});
test('Markermeer station level cannot supply IJsselmeer depth',()=>{assert.equal(basinAt(p),'ijsselmeer');const station={lat:52.62,lon:5.26,basin:'markermeer',valueM:-.3,time:now};assert.equal(depthAt(p,[station],{now}).unknown,true);});
test('out of coverage or incomplete cells stay unknown',()=>{assert.equal(bottomAt({lat:51,lon:4}).unknown,true);const minimal={...data,width:1,height:1,data:Buffer.from([255,127]).toString('base64')};setBathymetry(minimal);assert.equal(bottomAt(p).unknown,true);setBathymetry(data);});

test('production data comes from raw GitHub, local uses relative asset',()=>{assert.equal(bathymetryDataUrl('bathymetry-metadata.json','sergehanssens.github.io').hostname,'raw.githubusercontent.com');assert.ok(bathymetryDataUrl('bathymetry-metadata.json','localhost').pathname.endsWith('/data/bathymetry-metadata.json'));});
test('refresh updates metadata, validates changed grids and keeps prior model on failure',async()=>{const originalFetch=globalThis.fetch;try{setBathymetry(data);let requests=[];const checkedAt='2026-10-08T22:00:00Z';globalThis.fetch=async(url,options)=>{requests.push(String(url));assert.equal(options.cache,'no-store');return new Response(JSON.stringify({...data,data:undefined,checkedAt}));};await refreshBathymetry();assert.equal(requests.length,1);assert.equal(getBathymetryMetadata().checkedAt,checkedAt);
 const changed={...data,sourceSHA256:'b'.repeat(64),surveyYear:2023};requests=[];globalThis.fetch=async url=>{requests.push(String(url));return String(url).includes('metadata')?new Response(JSON.stringify({...changed,data:undefined})):new Response(zlib.gzipSync(JSON.stringify(changed)));};await refreshBathymetry();assert.equal(requests.length,2);assert.equal(getBathymetryMetadata().sourceSHA256,changed.sourceSHA256);
 globalThis.fetch=async url=>String(url).includes('metadata')?new Response(JSON.stringify({...changed,sourceSHA256:'c'.repeat(64),data:undefined})):new Response(zlib.gzipSync(JSON.stringify({...changed,sourceSHA256:'c'.repeat(64),width:1})));await assert.rejects(refreshBathymetry());assert.equal(getBathymetryMetadata().sourceSHA256,changed.sourceSHA256);
 globalThis.fetch=async()=>{throw new Error('offline');};await assert.rejects(refreshBathymetry());assert.equal(getBathymetryMetadata().sourceSHA256,changed.sourceSHA256);
 }finally{globalThis.fetch=originalFetch;setBathymetry(data);}});

