import assert from 'node:assert/strict';
import {parseWaterLevel,fetchWaterLevels} from './water-levels.js';
const now=Date.parse('2026-10-08T20:00:00Z'),station={code:'test',name:'Test',lat:52.7,lon:5.3};
const series=(overrides={},measurement={})=>({Locatie:{Code:'test'},AquoMetadata:{Grootheid:{Code:'WATHTE'},Hoedanigheid:{Code:'NAP'},ProcesType:'meting',Eenheid:{Code:'cm'},WaardeBewerkingsMethode:{Code:'NVT'},...overrides},MetingenLijst:[{Meetwaarde:{Waarde_Numeriek:-26},Tijdstip:'2026-10-08T19:50:00Z',WaarnemingMetadata:{Kwaliteitswaardecode:'00'},...measurement}]});
const parse=s=>parseWaterLevel({WaarnemingenLijst:[s]},station,now);
assert.equal(parse(series()).levelM,-.26);assert.equal(parse(series()).stale,false);
assert.equal(parse(series({Hoedanigheid:{Code:'MSL'}})).levelM,null);
assert.equal(parse(series({ProcesType:'verwachting'})).levelM,null);
assert.equal(parse(series({Eenheid:{Code:'unknown'}})).levelM,null);
assert.equal(parse(series({WaardeBewerkingsMethode:{Code:'GEM24H'}})).levelM,null);
assert.equal(parse(series({}, {Meetwaarde:{Waarde_Numeriek:999999999}})).levelM,null);
assert.equal(parse(series({}, {Meetwaarde:{Waarde_Numeriek:null}})).levelM,null);
assert.equal(parse(series({}, {WaarnemingMetadata:{Kwaliteitswaardecode:'99'}})).levelM,null);
assert.equal(parse(series({}, {Tijdstip:'2026-10-08T21:00:00Z'})).levelM,null);
assert.equal(parse(series({}, {Tijdstip:'2026-10-08T19:20:00Z'})).stale,true);
assert.equal(parse(series({Eenheid:{Code:'m'}}, {Meetwaarde:{Waarde_Numeriek:-.26}})).levelM,-.26);
const snapshot=await fetchWaterLevels({mode:'snapshot',now,fetcher:async()=>({ok:true,json:async()=>({fetchedAt:'2026-10-08T19:55:00Z',stations:[{timestamp:'2026-10-08T19:00:00Z',levelM:-.2}]})})});
assert.equal(snapshot.stations[0].stale,true);
console.log('Water-level validation passed: NAP, unit conversion, missing values, quality, stale and future timestamps.');
